### ISSUE TITLE
Time bound promotions

### ISSUE THREAD

**Issue by dhruvsharma-nyu-stern** [promotions-squad/promotions#11]
**Description:**

**As** the merchant
**I want to** be able to set a starting date-time and an ending date-time for a promotion 
**so that** I can create a time-bound promotion offer.

**Assumptions:**

* The merchants current time zone will be used to default the Day/Date Format and Time Zone

**Acceptance Criteria:**

When I create a new promotion record
And my merchant profile has a time zone associated with it
Then I should be able to set a Promotion Start and Promotion End Date & Time defaulted to my Time Zone.

**Comment by elizaevesophia** [comment]
Closing; will replace with new format for Sprint 2.
