### ISSUE TITLE
Create a new Space in your Cloud Foundry account called: Prod

### ISSUE THREAD

**Issue by elizaevesophia** [promotions-squad/promotions#115]
**Description:**
As a developer, I need to have a new Space in Cloud Foundry called Prod so that I can deploy my code from production to dev. 

**Assumptions:**
This space will be used to push to the public after passing prior steps. 

**Acceptance Criteria:**
Space exists: code can be pushed.

**Comment by dhruvsharma-nyu-stern** [comment]
created "prod" space to mimic "dev" and assigned the same user access as per the "dev" space.
