### ISSUE TITLE
Retrieve a Promotion

### ISSUE THREAD

**Issue by scotthalperin** [promotions-squad/promotions#31]
**Description:**
As a customer, I want to know if there are available promotions for the product I have selected so that I pay the lowest price for my purchase

**Assumptions:**
- Promotions are stored along with product id
- Product ID is used to retrieve the promotion
- Only one promotion can be applied to a product (the customer should receive the largest possible discount)
- Promotions can be for a dollar amount or a %

**Acceptance Criteria:**
GET /promotions/{product_id} returns a discount for any available promotion

**Comment by cybao** [comment]
This is retrieving a promotion based on product id, should have a separate story on retrieving a promotion based on promotion id
