### ISSUE TITLE
View Promotions in Cart

### ISSUE THREAD

**Issue by scotthalperin** [promotions-squad/promotions#4]
**Description:** As a user, I want my cart to display any items that have promotions applied to them, so that I have an accurate view of the price of my order throughout the buying.

**Assumptions:**
- Cart displays individual item price as well as total price
- Cart is visible throughout the buyflow

**Acceptance Criteria:**
- When adding an item with no promotion to the cart, there is no indicator or message for that item in the cart regarding a promotion
- When adding an item with a promotional discount to the cart, the user can see which item is being discounted, and the amount of the discount.
- The total price of the cart accurately reflects the promotional items.

**Comment by elizaevesophia** [comment]
Per Grooming meeting, need to discuss with other teams because it intersects with their microservices. Will talk about in class on 3/5. This story is really about ensuring other teams are displaying our content correctly.

**Comment by elizaevesophia** [comment]
Discussed with John; we don't need to worry about UI for now.
