### ISSUE TITLE
List all items applicable to a promotion

### ISSUE THREAD

**Issue by cybao** [promotions-squad/promotions#6]
**Description:**
As I buyer, I want to be able to see all of the items applicable to a promotion of my choice aggregated / filtered on the shopping page, so that I am aware of all items that are on sale

**Assumptions:**
- There are usually multiple items applicable to a promotion

**Acceptance Criteria:**
- When I click on a promotion, I will be brought to a page with a list of products
- The products included on the page are all that are applicable to the promotion I clicked

**Comment by elizaevesophia** [comment]
Functionally: need to send a list of all products that a discount applies to.

**Comment by cybao** [comment]
This is implemented by the productid attribute in the data model.
