### ISSUE TITLE
Add persistent storage

### ISSUE THREAD

**Issue by dhruvsharma-nyu-stern** [promotions-squad/promotions#69]
**As a** User
**I need** the application database to store my data
**So that** if one of the many application containers restarts, then my data is not lost

**Assumptions:**
* User data is stored in a database and not in memory
* We can use one of the below DB’s
   * IBM DB2
   * PostgreSQL* (elephantsql.com)
   * Cloudant / CouchDB (No SQL)
* Must use Docker for the DB Installation
* Credentials should come from VCAP_SERVICES or DATABASE-URI depending on what DB we choose.
* Service code should not be aware that the model now has persistence
* Same test cases and service.py should still work as expected without change.

**Acceptance Criteria:**

* Given the application is running with persistence
* When a user adds data to the app
* Then the data is still there when the app restarts (Counter example)

**Comment by elizaevesophia** [comment]
Closing this ticket but creating a new issue for debugging.
