### ISSUE TITLE
Displaying promotion information on the product page

### ISSUE THREAD

**Issue by cybao** [promotions-squad/promotions#7]
**Description:**

As a buyer, I want to be able to see all promotion information on the product page if applicable, so that I am informed of the duration of the promotion and the type of promotion available for the product.

**Assumptions:**
- There is a finite period of each promotion: starting date and end date
- The product could have zero, one or more promotion going on at the same time

**Acceptance Criteria:**
- On the product page, all current and future applicable promotions are listed in the promotion section
- Each promotion is listed with promotion type (BOGO, % off etc) and duration

**Comment by elizaevesophia** [comment]
Grooming notes:
- Each promotion has a link to a description and an aggregated list of all applicable products (part of aggregated promotion Story)
- If multiple promotions are applicable to a product, current promotions are listed first (will be added as enhancement)
- If multiple promotions are current for a product, promotion ending earliest is listed first (Will be added as enhancement)

**Comment by elizaevesophia** [comment]
UI story; closing in favor of stories that are more specifically and concisely written
