### ISSUE TITLE
Add Continuous Integration (CI) so that Pull Requests run test cases

### ISSUE THREAD

**Issue by dhruvsharma-nyu-stern** [promotions-squad/promotions#70]
**Description:**

**As a** developer
**I need to** set up continuous integration using Travis CI
**So that** When I create a pull request the tests are automatically run and once the pull request is accepted the master branch is always ready to deploy.

**Assumptions:**

* We will have a free TravisCI account setup
* The .travis.yml file should be set up so that the test cases run every time someone pushes to the master branch or submits a Pull Request. 
* A badge will be added to the repository's Readme.md file

**Acceptance Criteria:**

**When** I create a pull request to merge with the master branch
**Then** Travis CI will automatically run my test suite and provide the test results

**Comment by cybao** [comment]
Currently blocked on this issue because we need to fix the bug in test code first

**Comment by elizaevesophia** [comment]
@cybao , why are you calling this an enhancement instead of tech debt? This wouldn't be visible to end users and just improves developers' lives, right?

**Comment by elizaevesophia** [comment]
Update: discussed with John via slack and confirmed this ticket should be flagged as Tech Debt.
