### ISSUE TITLE
Create a Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by dhruvsharma-nyu-stern** [promotions-squad/promotions#71]
**Description:**
**As a** developer
**I need** to deploy my application to the cloud
**So that** the world sees our work and we can use the advantage of the horizontal scaling capabilities of the cloud

**Assumptions:**
* Use the singular version for resource name (e.g., orders becomes order)
* Prefixed by nyu- and suffixed by -service-s19
* Please name our IBM Cloud microservice nyu-promotion-service-s19
* The full URL will then be nyu-promotion-service-s19.mybluemix.net
* Use location Dallas to host
* Use at least 2 instances

**Acceptance Criteria:**
When I create the app in IBM Cloud
Then I do not get any errors and the status should be running. Also, when I visit the app URL, it should conform to the above URL standards mentioned in the assumptions section.

**Comment by dhruvsharma-nyu-stern** [comment]
Calling out the below steps that need to be done as part of this issue.

Create a database service for your Cloud Foundry app
Bind the database service to the Cloud Foundry app

**Comment by cybao** [comment]
Waiting for:
1) John's instruction on access group in bluemix
2) Persistent storage set up by Dhruv

**Comment by cybao** [comment]
Reassign this story to Dhruv
