### ISSUE TITLE
Failed test: Bad Request Error from Find By Product

### ISSUE THREAD

**Issue by elizaevesophia** [promotions-squad/promotions#72]
**Description:**
As a user, if I send a bad request, I should see an appropriate error message so that I understand what I've done wrong in my request. 

As a developer, I should see the appropriate label for this test: it should indicate that the failure occurred for Find by Promotion, not Product. 

**Assumptions:**
The Test a Bad Request error test case is correctly testing error generation. 

**Acceptance Criteria:**
When a bad find by promotion query is sent, the appropriate error message is generated. When the test code is run, developers see the appropriate label.

**Comment by cybao** [comment]
I think the test was mislabeled, the actual functionality should be searching by promotion id
We are creating a separate story for adding the search by product id test

**Comment by elizaevesophia** [comment]
Updated story to reflect fixing both the bug and the label.
