### ISSUE TITLE
Fix test server to increase code coverage

### ISSUE THREAD

**Issue by scotthalperin** [promotions-squad/promotions#75]
As a developer I want the API to work as expected so I can use the promotions functionality on the website.

Assumptions:
- Working means code coverage is above 95% and major test cases are passing
- Failing tests can be fixed as bugs in next sprint

Acceptance Criteria
95% code coverage
90% of tests passing

**Comment by elizaevesophia** [comment]
@scotthalperin , can you take another look at this one--I'm not following exactly what this issue fixed (or should it be marked as a duplicate with the linked tickets?) Additionally, if it's technical debt, I think we should write teh story form the perspective of the developer.

**Comment by scotthalperin** [comment]
@elizaevesophia updated the description - this was the work that was done to get us to meet the requirements for Homework 1
