### ISSUE TITLE
Download and install the IBM Cloud CLI in the Vagrant VM

### ISSUE THREAD

**Issue by dhruvsharma-nyu-stern** [promotions-squad/promotions#76]
**Description:**

**As a** developer
**I need** to have IBM Cloud CLI in our Vagrant VM to push code to the cloud

**Assumptions:**

* The Vagrantfile needs to be updated
* Cloud Foundry metadata files for deployment need to be created (manifest.yml, Procfile, runtime.txt) file so that IBM Cloud will know how to deploy our application.

**Acceptance Criteria:**

**When** we use the cf push command
**It should** push the application on the cloud and our URL should work

**Comment by cybao** [comment]
@dhruvsharma-nyu-stern this issue needs a label as well
