### ISSUE TITLE
Dollar based promotion

### ISSUE THREAD

**Issue by elizaevesophia** [promotions-squad/promotions#8]
**Description:**
As the merchant, I want to be able to take a dollar amount off an item so that I can offer promotions on specific items.

**Assumptions:**
Users will want to calculate discounts based on dollar, not percentage
Users will not be able to reduce price below $0. 
Modified prices will appear everywhere they are needed to

**Acceptance Criteria:**
When user enters a dollar amount to discount price, price is changed in promotions and all downstream microservices. 
Promotion price appears to customers when viewing item and in cart.

**Comment by cybao** [comment]
Redundant and we are not implementing separate class for this
