### ISSUE TITLE
Test for Read a promotion

### ISSUE THREAD

**Issue by elizaevesophia** [promotions-squad/promotions#89]
**As a** user, **I want** to search for a promotion **so that** I can get details about a specific promotion.

Assumptions:
The test files and code for actions already exist

Acceptance criteria:
**Given** I can request a specific promotion
**When** I send a READ request,
**Then** I will receive the details of the promotion. 

Note: written in the format we would use for future development, but issue itself is to **develop a test**, not the action.

**Comment by cybao** [comment]
so this would be listing individual promotions with their promotion id?

**Comment by elizaevesophia** [comment]
Yeah, does that make sense? There's already a test for it in features as part of update, so I was going to use that.

**Comment by cybao** [comment]
Sounds good. As we create steps, we should eventually have enough of them that we just need to write new scenarios in the feature without touching the steps file
