### ISSUE TITLE
Test for Cancelling a Promotion

### ISSUE THREAD

**Issue by elizaevesophia** [promotions-squad/promotions#95]
**As a** user, **I want** to cancel a promotion **so that** the promotion is no longer available for products.

Assumptions:
The test files and code already exist

Acceptance criteria:
**Given** that the availability flag exists
**When** I cancel a promotion
**Then** the promotion will be updated to reflect available = no. 

Note: written in the format we would use for future development, but issue itself is to **develop a test**, not the action.

**Comment by dhruvsharma-nyu-stern** [comment]
Will I need to create a Cancel a promotion button on the UI for this, please?

**Comment by dhruvsharma-nyu-stern** [comment]
Will I need to create a Cancel a promotion button on the UI for this, please?

P.S. Closed the issue by mistake earlier
