### ISSUE TITLE
Create a UI for testing with Selenium

### ISSUE THREAD

**Issue by elizaevesophia** [promotions-squad/promotions#97]
**As a** developer, **I want** to test with Selenium **so that** I can ensure my code meets the behavior expected by the end-user. 

Assumptions:
The tests match the user's expectations. 

Acceptance criteria:
**Given** the code exists
**When** I access the UI
**Then** I can run all of the tests

**Comment by cybao** [comment]
The UI for testing with Selenium is all set up with a local redis persistent storage. I have moved the bluemix related code (service/ and test/) into the bluemix/ folder to not interfere with what we are doing for this sprint.

Still need to to:

- Write a few more tests to increase code coverage from 93% to 95%
- Create/modify all the BDD files
